### ISSUE TITLE
應提供 requirements.txt

### ISSUE THREAD

**Issue by linroex** [TTPLP/Project-Yahoo-News-Crawler-hitler11319#6]

**Comment by linroex** [comment]
你不覺得你的 requirements.txt 內容怪怪的，多得不太正常嗎XD

**Comment by AugustHong** [comment]
我覺得還好啊！跟學長給我看的差不多

**Comment by AugustHong** [comment]
啊！我沒進虛擬環境對不對！

**Comment by AugustHong** [comment]
改好了

**Comment by linroex** [comment]
答對了，不過你到底在虛擬環境裡面裝了多少無用的東西呀XDD
以這邊來說，你應該只有用到 requests ？

**Comment by AugustHong** [comment]
呵呵！我建了虛擬環境後，就想：把以前你給我要我裝的都裝進去好了！就變成這樣了！（有要刪掉嗎？）

**Comment by linroex** [comment]
當然需要刪掉，你要思考，你現在這個專案用到哪些功能，就應該只有那些套件而已

**Comment by AugustHong** [comment]
弄好了！但wheel是本來就會在的對吧！
